# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Site settings
title: Making Space With Data
name: Angelo Varlotta
tagline: A blog on data insights
description: "Freelance Data Scientist &middot; PhD in Physics &middot; Data Science &middot; Data Visualization &middot; Machine Learning"
url: "http://angelovarlotta.com"
baseurl: ""

# About
author:
  name: Angelo Varlotta

# Social media URLs
linkedin_url:  https://www.linkedin.com/in/angelovarlotta/
github_url:  https://github.com/capac/
googlescholar_url:  https://scholar.google.com/citations?user=4X9H95cAAAAJ

# Build settings
theme: jekyll-theme-lanyon
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-gist

# Pagination
paginate: 5
paginate_path: "/blog/page:num"

# Permalink
permalink: /:categories/:title/

# Exclude from processing.
exclude:
  - .sass-cache/
  - Gemfile
  - Gemfile.lock

# Google Analytics tracking ID
google_analytics: UA-175596085-1
